### ISSUE TITLE
Didn't create iso file, for running. Has archiso package changed or is there missing steps?

### ISSUE THREAD

**Issue by thepenguinthatwants** [benmezger/archiso#1]
Hi I tried to create an iso using ur repo.
from command 

sudo mkarchiso -v -w archiso-out -o out ./archiso

There seem to be some errors as it stopped into here.

```
bw get item c553f8b1-f4a3-4220-8b0b-acb500c08fff: exec: "bw": executable file not found in $PATH
chezmoi: template: /home/seds/dotfiles/dot_authinfo.tmpl:1:57: executing "/home/seds/dotfiles/dot_authinfo.tmpl" at <bitwarden "item" .bitwarden.personal_mail>: error calling bitwarden: bw get item c553f8b1-f4a3-4220-8b0b-acb500c08fff: exec: "bw": executable file not found in $PATH


```

**Comment by benmezger** [comment]
This should be fixed with c3918c3. The error happened because my current [dotfiles](https://github.com/benmezger/dotfiles/blob/main/.chezmoi.yaml.tmpl#L2) sets `secrets` to true by default and tries to apply any related secrets.
